name: contacts
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  animations: ^2.0.2
  flutter_riverpod: ^1.0.3
  mask_text_input_formatter: ^2.1.0
  flutter_hooks: ^0.18.2+1
  flutter_quill: ^4.0.10
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


